version: '3'

services:
    amq-client:
        image: hnakra/azure-uamqp-php-build:1.2.0
        container_name: azure-amq
        build: /
        stdin_open: true
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./src:/var/www/html/example
