version: '3'

services:
    amq-client-redhat-os:
        image: hnakra/azure-uamqp-php-build-redhat-os:1.0.1
        container_name: azure-amq-redhat
        build: ./docker/redhat-os
        stdin_open: true
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./src:/var/www/html/example
            - .:/var/www/azure-uamqp-php
        # command: bash -c ""
